version: "3.9"
services:
  postgres:
    image: postgres:16-alpine3.20
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./.postgres_data:${PGDATA}
    restart: "always"

  fast-api:
    build:
      context: .
      dockerfile: ./apps/Dockerfile
    container_name: fast-api
    command: uvicorn apps.main:app --reload --host 0.0.0.0
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "${FAST_API_PORT}:${FAST_API_PORT}"
    depends_on:
      - postgres
    restart: "always"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env
    ports:
      - "${PGADMIN_DEFAULT_PORT}:${PGADMIN_DEFAULT_PORT}"
    depends_on:
      - postgres
    restart: "always"